### ISSUE TITLE
Feature request: option to bypass or tune SAN validation

### ISSUE THREAD

**Issue by vistomin** [postfinance/kubelet-csr-approver#70] opened 2022-07-01 08:55 UTC
Hi,

could you please add an option to bypass or tune SAN validation?
Currently CSR are being denied with the following reason:

```
> kubectl get csr csr-zwzjd -ojson | jq '.status.conditions[] | {message,reason,type}' 
{
  "message": "CSR not complying with kubelet-csr-approver validation process. Reason: The x509 Cert Request contains more than 1 DNS name",
  "reason": "kubelet-serving cert denied",
  "type": "Denied"
}
```
The SAN part of the request looks like:
```
                X509v3 Subject Alternative Name: 
                    DNS:ec2-1-2-3-4.eu-central-1.compute.amazonaws.com, DNS:ip-192-168-5-6.eu-central-1.compute.internal, IP Address:192.168.5.6, IP Address:1.2.3.4
```
I am not aware of any way to influence that, even though in my case public names/IPs are not needed.  The easiest would be to have an option to bypass this check or tune the allowed value, ie. making it greater than 1.

**Comment by nce** [comment] 2022-07-05 17:25
I'm having the same problem and was wondering if this behaviour (from aws/OS) is new:

```
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:ec2-54-93-174-213.eu-central-1.compute.amazonaws.com, DNS:i-0154a083baeceb204.eu-central-1.compute.internal, IP Address:10.10.164.36, IP Address:10.10.164.76, IP Address:10.10.169.203, IP Address:10.10.171.199, IP Address:54.93.174.213
```

I switched to [RBN hostnames](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-instance-naming.html#instance-naming-choose) and always figured, this was causing problems. But apparently it's the same with IP based names.

I then [tried a few things relating](https://github.com/nce/k8s-hard-way/issues/37) to aws-vpc-cni or aws-cloud-controller changes, but the problem remains. I'm unaware if this is influeced by aws instance/dhcp/dns configuration. My setup is running the alpha channel of flatcar as OS.

Allowing multiple of those DNS SANs shouldn't compromise security of the controller. Especially if we could fine tune (think of regex) whitelisting these entries. But i'm fine with everything solving this issue.

**Comment by jkroepke** [comment] 2022-07-07 12:40
Possible workaround: Disable the public IP on the node

**Comment by nce** [comment] 2022-07-07 13:00
As discussed with @jkroepke; this was indeed my fault. The Node is placed in a private subnet, with access to a NAT Gateway. Unfortunately i forgot to disable the public ip on this instance (which i used beforehand).

The issue is fixed for my setup by providing a private subnet with `map_public_ip_on_launch                     = false` and the instance with `associate_public_ip_address = true`(!)

This results in:
```
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:i-0d106130395aded94.eu-central-1.compute.internal, IP Address:10.10.183.35
``` 

Apart from the mentioned changes i didn't modify anything. This was a configuration issue on my side, sorry.

**Comment by clementnuss** [comment] 2022-07-07 16:35
hi,

this seems like a valid point 👍🏻 will address that in the coming days with a config option

**Comment by clementnuss** [comment] 2022-07-25 12:28
hi @vistomin 

I've implemented a new config flag that permits allowing more than 1 DNS name to be processed: `--allowed-dns-names`

to use it, simply add the `--allowed-dns-names 10` argument when running kubelet-csr-approver, or specify the config as an environment variable (`ALLOWED_DNS_NAMES=10`)

can you report whether this works for you using the following image please?
```
docker.io/postfinance/kubelet-csr-approver:multiple-dns@sha256:a9c0f91531325ec9404ae30fa7f1055ec226f2c426e660ba7bc91bfaa675075a
```

**Comment by vistomin** [comment] 2022-07-28 11:17
hi @clementnuss,

this works like a charm!  Thanks!

**Comment by clementnuss** [comment] 2022-08-22 08:36
the feature is now on the main branch, closing this issue !

**Closed by clementnuss** 2022-08-22 08:36 UTC
